### ISSUE TITLE
Upgrade to latest Firebase version

### ISSUE THREAD

**Issue by pavadeli** [skunkteam/sherlock#49]
Recently, the Firebase SDK has changed their interfaces significantly. We need to update `ngx-sherfire` to reflect this in order to be compatible with the latest version.

**Comment by Askamp** [comment]
Ik mag dit sherlock issue in projects wel slepen naar een andere lane, maar bij bijv labels en assignees krijg ik user does not have permission.

**Comment by pavadeli** [comment]
Opgelost in #50
